services:
  backend:
    image: node:18
    working_dir: /app
    command: npm start
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - EMAIL_USER=as9467665000@gmail.com
      - EMAIL_PASS=ddle kjkt haxu vfmz
      - DJANGO_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQyMjM3MzE0LCJpYXQiOjE3NDIyMzU1MTQsImp0aSI6IjU0NzU3YTQ2NTI4YzRjZjg5OGRkY2NlMmMzZTMzOGU3IiwidXNlcl9pZCI6MX0.QiJ5gnltUvZV3vtonfH4BRJAdz2NnshEDL0z_arjxIQ
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: bharat_digital_user
      POSTGRES_PASSWORD: w4dr995RrBqbMIRvgedNHGkUovf1JoFB
      POSTGRES_DB: bharat_digital
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
